String? messageFiled = "هذا الحقل مطلوب";
String? messageMatcherPassword = "كلمات المرور غير متوافقة";
String? messageMatcherEmail = "هذا الايميل غير صالح ";
String? errorPasswordLength = "كلمة المرور يجب ان تكون اكبر من 6 حروف ";
String? error = "خطأ";
String? txtCancel = "Cancel";
String? txtWait = "please wait...";
String? txtLogout = "Logout";
String? txtLogoutHint = "are you sure that you want Logout";
String? txtConnection = " انت بلا انترنت  ";
String? txtConnectionNote = " كل العمليات التي ستقوم بها سيتم تخزينها على الهاتف وفي حال اتصالك بالانترنت سيتم تنفيذها  ";

//todo this for login page
String? txtWelcome = "Welcome,";
String? txtSignUp = "Sign Up";
String? txtSignIn = "Sign In";
String? txtSignInContinue = "Sign in to Continue";
String? txtName = "Name";
String? txtEmail = "Email";
String? txtPassword= "Password";
String? txtForgotPassword= "Forgot Password?";
String? txtOr= "-OR-";
String? txtFacebook= "Sign In with Facebook";
String? txtGoogle= "Sign In with Google";
String? txtError= "Error";
String? txtSuccess= "Success";



String txtContinue = "Continue";
String txtWhatsIsyourMobileNumber = "What is your Phone Number?";
String txtlanguage = "language";
const String txtErrorMobileNumber = "Enter A valid Mobile Number";
const String txtResned = "resend";
const String txtResendCodeIn = "Resend code in ";
const String txtEnterYourPasscode = "Enter Your Passcode";
const String txtChooseCountry = "Choose Country";
const String txtSearchForCountry = "Search For Country";
const String txtEditProfile = "Edit Profile";
const String txtLog = "log";
const String txtLogOut = "logOut";
const String txtSetting = "setting";
const String txtFullName = "full name";
const String txtErrorFillYourName = "fill your name";
const String txtErrorFillYourEmail = "fill your Email";
const String txtAlternativeContact = "Alternative Contact";
const String txtSave = "Save";
const String txtSelectImage = "Select Image";
const String txtCamera = "Camera";
const String txtGallery = "Gallery";
const String txtTirms = "tirms";
const String txtAboutInbox = "About Inbox";
const String txtHelpCenter= "Help Center";
const String txtProfile = "Profile";
const String txtLogOutChecking = "Are You Sure You Want to LogOut ?";
const String txtChangeMobileNumber = "Change Mobile Number";
const String txtWhatIsYourNewPhoneNumber = "What is your New Phone Number ?";
const String txtOk = "OK";
const String txtSelect = "Select";